SELECT TOP (1000) [F1]
      ,[Order ID]
      ,[Product]
      ,[Quantity Ordered]
      ,[Price Each]
      ,[Order Date]
      ,[Purchase Address]
      ,[Month]
      ,[Sales]
      ,[City]
      ,[Hour]
  FROM [SalesData].[dbo].['Sales Data']


  SELECT * FROM [SalesData].[dbo].['Sales Data']

  ----What is the total revenue generated by each product?

SELECT PRODUCT, 
       SUM([Quantity Ordered] * [Price Each]) AS TotalRevenue
FROM [SalesData].[dbo].['Sales Data']
GROUP BY PRODUCT
ORDER BY TotalRevenue DESC;

--Which product has the highest sales volume, and which has the highest revenue?
SELECT 
    Product, 
    SUM([Quantity Ordered]) AS Total_Sales_Volume
FROM 
    [SalesData].[dbo].['Sales Data']
GROUP BY 
    Product
ORDER BY 
    Total_Sales_Volume DESC

	--Which month has the highest total sales?

	select sum(sales) as highestsales, MONTH
	from [SalesData].[dbo].['Sales Data']
	group by MONTH
	order by highestsales desc


	--How does sales performance vary by hour of the day? When is the peak ordering time?

	select hour , sum(sales) as sales_performance_per_hour
	from [SalesData].[dbo].['Sales Data']
	group by hour
	order by sales_performance_per_hour desc

	----Are there any trends in sales over different months or specific dates?
	SELECT 
    Month, 
    SUM(Sales) AS Total_Sales
FROM 
	[SalesData].[dbo].['Sales Data']
GROUP BY 
    Month
ORDER BY 
    Month;

	SELECT 
    [Order Date], 
    SUM(Sales) AS Total_Sales
FROM 
   [SalesData].[dbo].['Sales Data']
GROUP BY 
    [Order Date]
ORDER BY 
    Total_Sales desc


--Which city has the highest number of orders?
SELECT 
    City, 
    COUNT([Order ID]) AS Number_of_Orders
FROM 
    [SalesData].[dbo].['Sales Data']
GROUP BY 
    City
ORDER BY 
    Number_of_Orders DESC




	--How does the average quantity ordered vary by product and city?
	select AVG([quantity ordered]) as avg_order, PRODUCT, city
	from  
		[SalesData].[dbo].['Sales Data']

	group by 
		Product, City
	order by
		avg_order DESC


--Can you identify repeat customers based on the 'Purchase Address' or other criteria?

 SELECT * FROM [SalesData].[dbo].['Sales Data']

 SELECT [Purchase Address] AS Address, 
       COUNT(*) AS Repeat_Customer
FROM [SalesData].[dbo].['Sales Data']
GROUP BY [Purchase Address]
ORDER BY Repeat_Customer DESC;


--What is the total revenue generated in each city?
SELECT * FROM [SalesData].[dbo].['Sales Data']

select sum([quantity ordered] * [price each]) as total_revenue, city 
from 
	[SalesData].[dbo].['Sales Data']
group by 
	city 
order by 
	total_revenue desc

--How does the average order value differ across cities?

select * from [SalesData].[dbo].['Sales Data']

select avg([quantity ordered] * [price each]) as avg_order_value, city 
from [SalesData].[dbo].['Sales Data']
group by 
City
order by avg_order_value